export const TOKEN_RECIEVED = "TOKEN_RECIEVED";
export const TOKEN_EXPIRED = "TOKEN_EXPIRED";
export const MUNICIPALITY_TOKEN_RECIEVED = "TOKEN_RECIEVED";
export const MUNICIPALITY_TOKEN_EXPIRED = "TOKEN_EXPIRED";
export const SNACKBAR_OPEN = "SNACKBAR_OPEN";
export const SNACKBAR_CLOSE = "SNACKBAR_CLOSE";
